### ISSUE TITLE
A sgerrand.rsa.pub URL update

### ISSUE THREAD

**Issue by gatorjh** [bnc-projects/base-openjdk#6]
As noted [here](https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub), the URL https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub needs to be updated to https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub

**Comment by alphafoobar** [comment]
Links 404.
